mercurius-js/mercurius

- README.md
- index.js
- routes.js
- test/routes.js
The redirection is incorrect if the plugin is registered with a prefix. 
This PR fixes the issue ;)
> fix(routes): graphiql redirection if a prefix have been set

- index.js
- test/plugin-definition.js
There is no plugin definition which makes dependencies resolution not working if a plugin depends on `fastify-gql`
> Plugin name definition

- README.md
- index.js
- routes.js
- tap-snapshots/test-routes.js-TAP.test.js
- test/routes.js
This PR adds the errorHandler option to fastify-gql in order to allow custom error handling.
With test and documentation.
> Handle errors according to graphql spec and allow custom error handling

- static/graphiql.html
The fastify prefix option doesn't affect the graphiql's static page when consuming graphql endpoint.
> Uses the relative path to prevent error 404 when a prefix is used

- README.md
Just fixed a typo in README, thank you
> docs: typo in require makeExecutableSchema  example

- lib/subscriber.js
- test/subscriber.js
In some rare cases there's a possibility when `close` will be called before `subscribe` will happen. In this case that error could cause even app server crash. Also it prevents `this.queue.destroy()` to be called.
I don't know how to properly test this case, cause it's caused by some abnormal behaviour of client side. Tried some options with closing ws client right after establishing connection, sending some crappy staff into it - nothing caused this bug to appear.
Anyway it's present and needed to be fixed.
> Fix TypeError: this.queue.close is not a function

- lib/subscription-connection.js
- lib/subscription.js
- package.json
- test/routes.js
- test/subscription-connection.js
- test/subscription.js
Update fastify-websockets to 1.x.x and fix tests.
> feat(deps): update fastify-websocket to 1.x.x, fix tests

- .gitignore
- README.md
- index.d.ts
- index.js
- lib/routes.js
- test/routes.js
- test/types/index.ts
I wanted to improve the clarity on the ide feature.
> Refactoring: improve ide usage clarity

- README.md
- index.d.ts
- index.js
- lib/routes.js
- test/routes.js
This PR tries to close #103 
I have not found a way of providing custom graphql endpoint to playground/graphiql.
@mcollina Could you help me with it?
> Feature: Add custom path into GQL constructor

- lib/routes.js
- tap-snapshots/test-routes.js-TAP.test.js
- test/routes.js
Only set error response status code when it is defined. Otherwise [response will be truncated.](https://github.com/fastify/fastify/issues/2078).
> fix: error handler setting undefined status code

- lib/routes.js
- test/routes.js
Instead of redirecting to static files, which will be accessible also with the "wrong" `ide` option value, it will serve the proper file: `playground.html` for `/playground` and `graphiql.html` for `graphiql`
Fixes #92
> Disables serving of static ide files

- lib/routes.js
- test/routes.js
GraphiQL wasn't rendering if `graphiql: true` option was set, as in examples.
It was working, though, with `ide: true` or `ide: 'graphiql'`
Refs: #89
> renders graphiql if graphiql: true option is set

- lib/queryDepth.js
- test/query-depth.js
@mcollina Not really sure if this new way of computing query depth covers all cases.
In the proposed test I used the following query
```
flavors {
id
name 
nutrition {
calories,
description {
body
other {
body
}
}
}
recipes {
name
ingredients {
name
}
}
seasons {
name
}
}
```
which have a depth of 4 (`flavors -> nutrition -> description -> other`)
Fixes: #105
> updates the way query depth is computed

- index.d.ts
- test/types/index.ts
This PR:
1. Improved TypeScripts types by naming the namespace and the plugin function using one symbol. This make sure that both the plugin its inner definitions (especially `Options`) are exported.
2 Fixed the return type of the graphql decorator. It was mistakenly reported as a fastify response, but it is actually the graphql execution result, and also it is always returned a promise.
Hope this helps!
> Improve Typescript definitions

- README.md
Updates the documentation and notes that the `queryDepth` value must be at least 7 if the introspection query should be allowed by the GraphiQL (or Playground) IDE. If it is smaller than 7 these queries will fail.
> Update `queryDepth` option docs

- README.md
- index.d.ts
- index.js
- lib/errors.js
- lib/routes.js
- test/errors.js
- test/types/index.ts
This is a PR for adding feature described in #144 
I'd like for some input on my implementation and naming. 
- Is `FastifyGraphQLError` class for the extended error suitable?
- How should we structure the error parameters? At the moment I'm using Apollo's `ApolloError` format; i.e. `(message: string, code: string, additionalProperties: object)`
> Extended errors

- lib/gateway/request.js
- test/gateway/request.js
Graphql errors in the gateway are not handled in any way. So response on underlying error will be like 
```json
{
"error": {
"errors": [
{
"message": "Cannot read property 'foo' of null",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"payments"
]
}
],
"data": null
}
}
```
Instead, with this change, we will see something like
```json
{
"error": {
"errors": [
{
"message": "Unexpected error value: [{ message: \"invalid token\", locations: [Array], path: [Array], extensions: [Object] }]",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"foo"
]
}
],
"data": null
}
}
```
which will slightly improve debugging experience
> feat: improve error handling for federation queries

- index.js
- test/routes.js
I found an inconsistency in returned error codes when handling user input errors. Syntax errors in queries will cause `Bad Request` (400) error, which is correct. However missing variables such as this example:
```js
const app = Fastify();
const schema = `
type Query {
add(x: Int, y: Int): Int
}
`;
const resolvers = {
add: async ({ x, y }) => x + y,
};
app.register(GQL, {
schema,
resolvers,
});
const query = "query ($x: Int!, $y: Int!) { add(x: $x, y: $y) }";
const res = await app.inject({
method: "GET",
url: `/graphql?query=${query}&variables=${JSON.stringify({ x: 5 })}`, // notice there's no 'y' 
});
```
Along with other errors related to query variables like mis-typed variables would cause `Internal Server Error` (500) errors which isn't correct since this problem is coming from the …
> Variable validation before query execution

- examples/gateway.js
- lib/gateway.js
- test/gateway/schema.js
When generating resolvers for fields with scalar return types, the gateway always assumed that the field is not on the `Query` or `Mutation` and created an `Entity` resolver. This resulted in an error (#158) when the schema contained a field like the following:
```
type Query {
hello: String
}
```
This PR adds a check to the resolver generation and if the field is on the `Query` or `Mutation` type it assigns the correct resolver.
> Generate correct resolver for fields returning scalar

- examples/gateway.js
- lib/federation.js
- lib/gateway/service-map.js
- tap-snapshots/test-federation.js-TAP.test.js
- test/gateway/extends-directive.js
- test/gateway/schema.js
Add support for `@extends` directive to federated services. With this change, it is possible to define a type extension in the following way:
```
type User @key(fields: "id") @extends {
id: ID! @external
post: Post
}
```
This is equivalent to the following:
```
extend type User @key(fields: "id") {
id: ID! @external
post: Post
}
```
This change is needed to be able to support federated services that are implemented with a graphql library that doesn't support the `extend` keyword (such as `graphql-java`).
> Add @extends directive support

- README.md
- index.d.ts
- index.js
- lib/errors.js
- test/errors.js
- test/types/index.ts
Fixes #164 
Removes explicit `code` field in `ErrorWithProps` and renames `additionalProperties` field to `extensions`.
> Fixes missing error extensions when query is jit'ed

- package.json
The `ws` package is also used in the `lib/gateway/service-map.js` module, it should be a dependency and not a devDependency
> fix: move ws from devDependencies to dependencies

- index.d.ts
- package.json
- tap-snapshots/test-federation.js-TAP.test.js
- tap-snapshots/test-reply-decorator.js-TAP.test.js
- tap-snapshots/test-routes.js-TAP.test.js
- test/app-decorator.js
- test/routes.js
This PR fixes the tests that are broken in #131.
The tests were broken because of changes in the error messages.
The Typescript check also failed because in the `node_modules/graphql-tools` package has two TS errors related to the schema stitching which is not used by this project at all. This can be avoided if the `IResolvers` type is not imported from the `graphql-tools` lib but included in the `types.d.ts` file.
> Update GraphQL to version 15.0.0

- README.md
- index.d.ts
- index.js
- test/validation-rules.js
Adds support for passing optional custom validationRules. Should enable usage of libraries like graphql-query-complexity.
> Add support for custom graphql validation rules

- test/routes.js
- test/subscription.js
I'm not particularly familiar with the codebase, so I'm not sure if this is the *proper* fix.
With these changes I no longer experience the failing tests.
---
At the time of this fix, these tests were passing on Travis, however,
failed on my Mac locally running on node v12.18.1.
After a little digging, the underlying error seemed to be related to
schema validation issues, occurring when calling validateSchema
function within app.ready(...).
It seems to be a valid error that happens when attempting to initialize
app with invalid schema, however, I'm unsure why I encountered it
and not other contributors (including CI).
> Fix failing tests

- README.md
- index.d.ts
- index.js
- test/app-decorator.js
`fastify-gql` currently keeps the schema it executes queries against private. If you want to execute GraphQL queries against your `fastify-gql` managed schema in another way, like in tests, from background jobs, or using your own protocol bindings of some sort, this is unfortunate! I think it makes sense to expose it so developers can access it and do whatever they need to with it. In the normal course of writing GraphQL apps this shouldn't be necessary, but it doesn't seem like `fastify-gql` needs to reserve the schema as an implementation detail since the type is already in use outside `fastify-gql`'s API boundaries.
This is currently on top of #190 to get the tests to pass, I'll rebase once that's merged for a clean master merge!
> Expose schema

- README.md
- index.d.ts
- index.js
- test/types/index.ts
- test/types/tsconfig.json
- test/validation-rules.js
Graphql validation context does not include variables and operationName, however those are often needed when defining custom validation rules.
These changes allow initializing custom validation rules and passing the the graphql request metadata in the function.
I'm using `params` as an object to make it easier to add new properties a bit easier in the future.
I'm a bit unsure if it's necessary to add extra validation for `opts.validationRules` to ensure it's a function and returned value an iterable.
> Allow using graphql request metadata when defining validationRules

- index.d.ts
- test/types/index.ts
[There is support for executableSchemas](https://github.com/mcollina/fastify-gql#makeexecutableschema-support), but the type definitions forces to define resolvers when it shouldn't.
> fix resolvers ts definition

- lib/routes.js
- test/routes.js
Respecting the GraphQL spec the operationName can be `null`.
https://spec.graphql.org/October2016/#GetOperation()
This error caused that when executing unnamed operations and the client sends the request with operationName = null, the servers responds:
```
{
"error": {
"errors": [
{
"message": "Unknown operation named \"\"."
}
],
"data": null
}
}
```
> fix operationName schema type

- lib/gateway/service-map.js
- test/gateway/schema.js
Currently if the SDL returned from the gateway's [`ServiceInfo`](https://github.com/mcollina/fastify-gql/blob/99a06a9ff480bc5aa8a6ab4b925b6d876f125645/lib/gateway/service-map.js#L67) query contains any directive definitions, the following error will be be thrown:
```js
TypeError: Cannot read property 'some' of undefined
```
This error originates from the [`hasDirective`](https://github.com/mcollina/fastify-gql/blob/99a06a9ff480bc5aa8a6ab4b925b6d876f125645/lib/gateway/service-map.js#L13) function, and is thrown because a [`DirectiveNode`](https://github.com/graphql/graphql-js/blob/6012d28b3b1fe8e002eefed9a3f013d4b352f08d/src/language/ast.js#L414) does not contain a `directives` field. 
Changes in this PR allow `hasDirective` to handle any …
> Allow hasDirective to handle nodes that do not contain directives.

- lib/federation.js
- lib/federation/compositionRules.js
- test/federation.js
This fixes https://github.com/mcollina/fastify-gql/issues/184
As discussed with @mcollina with this PR I'm going with the simplest fix just for the linked issue. 
We replicate Apollo's behaviour by moving validations in our code and skipping the `UniqueDirectivesPerLocationRule` rule.
> Remove UniqueDirectivesPerLocationRule from validation for federated schemas

- index.d.ts
- test/types/index.ts
ref: https://github.com/fastify/help/issues/227
I'll investigate later it has a bug on the cache. This should be added btw
> update(types): add cache map

- .gitignore
- index.d.ts
- index.js
- test/errors.js
- test/types/index.ts
I would like to switch all thrown errors to 200, but preserve the built in error formatting capabilities by doing:
```
errorFormatter: (err) => {
err.statusCode = 200
return defaultErrorFormatter(err)
},
```
> Expose defaultErrorFormatter

- README.md
- lib/gateway/service-map.js
- lib/subscription-client.js
- test/gateway/subscription.js
- test/subscription-client.js
This PR fixes the `gateway.service.wsConnectionParams` that is currently defined in the documentation but not handled.
It also adds the `connection_error` message handling for the `SubscriptionClient` and the `connectionInitPayload` option.
> fix: handle gateway.service.wsConnectionParams

- lib/gateway/make-resolver.js
- test/gateway/schema.js
This PR fixes the following use cases with fastify-gql gateway.
```graphql
mutation createTeam1($input1: CreateTeamInput!) {
createTeam(input: $input1){
team{
name
}
}
}
```
```
{
"input1": {
"team": {
"adminPersonId": "f18b72b0-e8f8-11ea-adc1-0242ac120002"
}
}
}
```
```graphql
mutation createTeam2($team: TeamInput!) {
createTeam(input: {
team: $team
}){
team{
name
}
}
}
```
```
{
"team": {
"adminPersonId": "f18b72b0-e8f8-11ea-adc1-0242ac120002"
}
}
```
> Support variables inside nested arguments in gateway resolver

- lib/subscription-client.js
- lib/subscription-protocol.js
- test/subscription-client.js
Some backend federated services like postgraphile.org send periodic keepalive message over websocket.
This fixes compatibility with such graphql servers.
> Fix websocket connection issues with postgraphile

- README.md
- lib/subscription-client.js
- test/subscription-client.js
This PR fixes the ready state of the `SubscriptionClient` that was not properly handled due to an invalid property set in the `close` function (`this.isReady = false` instead of `this.ready = false`). 
It also extends the `connectionCallback` usage to handle error payload in case of a `connection_error`.
> fix: handle SubscriptionClient ready state properly

- bench.sh
As `example.js` was [moved](https://github.com/mcollina/fastify-gql/commit/84b8254ae27c40920bce550508025e5873fe6e0a#diff-bfebe34154a0dfd9fc7b447fc9ed74e9) to `examples/basic.js`
> Fix ./bench.sh

- lib/gateway/service-map.js
- test/gateway/schema.js
The gateway can overwrite already defined types when calling `buildServiceMap`. 
I noticed the bug occurs if you define two Query returning a scalar.
I encountered this bug because I join the schema defined by multiple module before passing it to mercurius, so the service SDL contains multiple `extend Query`. Once the gateway schema is built the first `extend Query` doesn't have any resolver and skips the resolution to return `null` without forwarding the request to the related service.
> fix(gateway): should support multiple extends of the same type in the service SDL

- index.js
- test/app-decorator.js
`mercurius.defineResolvers` can fail to bind a resolver if it is not defined in the schema, this PR fails properly with the type and field name to help for debug
> feat: defineResolvers should throw if field is not defined in schema

- index.d.ts
- index.js
- test/federation.js
- test/types/index.ts
Addresses #300 
After digging into it a bit more, I realized that I already need the federated schema before calling `makeExecutableSchema` as described in the issue, due to having federation specific directives (like `@key` and `@external`) in the schema.
To support that use case, I'm exporting `buildFederationSchema` function that will allow me calling it to extend my schema with types, directives and resolvers needed to run in federation mode. I can then extend the federated schema with custom directives.
> Expose buildFederationSchema

- lib/gateway.js
- test/gateway/schema.js
An empty `_entities` response for `LIST_TYPE` currently produces the following error:  `Cannot read property 'json' of undefined`.
> test(gateway): support array references and empty reponse

- lib/gateway/make-resolver.js
- test/gateway/requires-directive.js
When extending a type defined in a separate service, the fields in the `@requires` directive are not being added to the query unless they are fetched by the client already.
This change looks at all the children of a field and adds any required fields to the parent's selection set
Example:
```
type User @key(fields: "id") @extends {
id: ID! @external
name: String @external
biography: String @requires(fields: "id name")
}
```
Currently, only `id` will be passed to `biography` because it's defined on `@key` (or if it's part of the client's query)
With this change, both `id` & `name` will be passed to `biography`
> fix(gateway): make parent field use @requires directive

- README.md
- lib/gateway/service-map.js
- test/gateway/schema.js
This PR adds an option to set request headers for the _service SDL query from gateway to services, similar to connectionInitPayload.
> feat(gateway): add initHeaders option for services

- docs/subscriptions.md
- index.js
- lib/subscriber.js
- lib/subscription.js
- test/subscription.js
This PR adds an utility function for filtered subscriptions, inspired by apollo's [withFilter](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#subscription-filters)
> feat(subscription): implement subscription filters

- docs/api/options.md
- docs/federation.md
- docs/loaders.md
- docsify/sidebar.md
I had difficulties finding loaders documentation in the new website, a search query leads to the federation documentation about the `__resolveReference` loader.
I think it deserves its own section in the sidebar.
> doc(loaders): enhance loaders documentation

- README.md
I think we should add this feature to the README, I don't know about any other graphql server that is capable of this feature for now.
> doc(README): add Federated subscriptions support

- README.md
- docs/api/options.md
- docs/federation.md
- docs/integrations/mercurius-integration-testing.md
- docs/integrations/nexus-schema.md
- docs/plugins.md
- index.d.ts
- index.html
- test/types/index.ts
- Added `bash` & `typescript` [language-lighting](https://docsify.js.org/#/language-highlight)
- Renamed `sh` tags to `bash` due to `Prism` not recognizing them properly
- Fix TOC reference in Federation docs
- Added `PubSub` to context & `app.graphql.pubsub`
- Improved Context types & allowing [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation)
- Added `app.graphql()` function signature
- Improved Loaders types
- Added `app.graphql.transformSchema(schemaTransforms)`
- Improved `MercuriusGatewayService` types
- Fixed `PeristedQueryProvider` typo, while keeping the old name but deprecated, to prevent breaking change. _I am not completely sure if it's really necessary_
- Minor change in `IResolvers` to fix [GraphQL …
> improve types & docs

- index.js
- lib/routes.js
- lib/subscription-connection.js
- lib/subscription.js
- test/gateway/pollingInterval.js
I noticed the subscription schema was never being refreshed because of how the schema was passed down to `subscription-connection`. After switching the schema usage to `fastify.schema` the schema correctly refreshes as expected.
There was an existing test that should have covered it, however, there was a mistake in the test itself. So adding additional tests seemed unnecessary.
> Fix refreshing subscription schema

- index.d.ts
- package.json
- test/types/index.ts
- tsconfig.json
- The included `pubsub.subscribe` actually returns a Node.js Readable (technically from `readable-stream`, but both are pretty much the same types)
- `withFilter` types were missing
> improve subscription types

- docs/api/options.md
- index.js
- lib/errors.js
- test/app-decorator.js
- test/gateway/methods.js
1 step to address the issue #348 
This PR prevent the usage of `extendSchema` if `federationMedata` is enabled
> fix(extendSchema): throw if federationMetadata is enabled

- docs/integrations/README.md
- docs/integrations/open-telemetry.md
- docs/open-telemetry.md
- docsify/sidebar.md
Waiting for `@opentelemetry/instrumentation-graphql` release.
> doc(opentelemetry): add tracing documentation with zipkin and opentelemetry

- docs/typescript.md
- docsify/sidebar.md
~~WIP~~
I made [https://github.com/mercurius-js/mercurius-typescript](https://github.com/mercurius-js/mercurius-typescript) for the code, to take inspiration, and testing the code while we are at it, ~~I think eventually that repo could be transferred to the org eventually too~~.
~~I am planning to at least add basic usage and [graphql-codegen](https://graphql-code-generator.com/) usage.~~
~~Maybe I can also add [nexus](https://nexusjs.org/) and [TypeGraphQL](https://typegraphql.com/) 🤔~~
---
Preview: https://pabloszx.github.io/mercurius/#/docs/typescript
> typescript docs

- docs/api/options.md
- docs/subscriptions.md
- index.d.ts
- index.js
- lib/subscriber.js
- test/subscription.js
- test/types/index.ts
I would like to use other emitter clients, which do not follow `mqemitter` api. This should enable that use case.
Related #350 
For now I've typed the pubsub option as `any`, since using the `PubSub` there would lead to an incorrect interface.
> Add support for passing custom pubsub

- package.json
Fix #360 
Generic type for graphql `ExecutionResult` was introduced here: https://github.com/graphql/graphql-js/pull/2626
> fix: Build with tsc updating graphql to 15.4.0

- docs/api/options.md
I had some problems with `subscriptions` on graphiql until I found #283. It would be better if have some notes to help instead of search for each every time. This PR provides it.
> docs(api/options): add a note to graphiql option

- docs/api/options.md
- examples/playground.js
- index.d.ts
- index.js
- lib/routes.js
- tap-snapshots/test-routes.js-TAP.test.js
- test/routes.js
- tsconfig.json
Adds a `playgroundHeaders` option which works with GraphQL playground and allows adding HTTP headers such as authorization.
It supports objects or, probably more useful, functions. The function version relies on the ability to serialize the function definition to a string, which is injected in the client side JS and invoked with the window object, basically allowing to extract headers from browser's storage or any place accessible to the client.
> feat: GraphQL playground headers

- docs/subscriptions.md
- lib/subscription.js
- test/subscription.js
Hi, thank you for the great library.
This PR fixes https://github.com/mercurius-js/mercurius/issues/369, which enables `mercurius` to work with `fastify-websocket`.
As @mcollina suggested on https://github.com/mercurius-js/mercurius/issues/369#issuecomment-751381695, I've added a check if `fastify-websocket` is already registered or not.
- My determination is that checking the decorator `fastify.websocketServer` is `undefined` or not. I think there should be a method to check a plugin registered or not, but this is what I know about Fastify.
- I've added a simple test for coverage. I've confirmed subscription is working even if `fastify-websocket` is already registered on my machine, but I'll happy to add more tests if needed.
Thanks!
> fix: Do not register fastify-websocket if it is already registered

- docs/api/options.md
- index.d.ts
- index.js
- lib/routes.js
- lib/subscription-connection.js
- lib/subscription.js
- test/routes.js
- test/subscription-connection.js
I was switching from Apollo Server to Mercurius, but I realized that the onDisconnect functionality that I used in Apollo Server which I used for cleanup in my app was missing from Mercurius. I saw a similar feature addition in #167 with the addition of onConnect, so I decided to add an onDisconnect alongside most places where I found onConnect, and so far it seems to be working.
In my use case, I need onDisconnect to be called with the context created by onConnect which contains the information I would need for cleanup, but I'm not sure if that's the best argument to pass to onDisconnect.
Thank you for your hard work on mercurius and I'm looking forward to using it! If there's any changes you'd like me to make with this PR, do let me know!
> feat: add subscription.onDisconnect callback for subscriptions

- lib/federation.js
- test/federation.js
Currently a gateway will throw a validation error if more than one federated service has the same directive defined - excluding directives added by `federationMetadata`. (ie. `Error: There can be only one directive named ...`)
While `compositionRules` does remove the `UniqueDirectivesPerLocationRule`, it is being circumvented by not passing `assumeValidSDL: true` to the `extendSchema` calls prior to the `validateSDL` call.
[This](https://github.com/mercurius-js/mercurius/blob/1ae98ad2d577e1a4d83a098544a21b358374d97c/lib/federation.js#L248) call of `extendSchema` is the direct cause of the issue, but based on [this](https://github.com/mercurius-js/mercurius/blob/1ae98ad2d577e1a4d83a098544a21b358374d97c/lib/federation.js#L259) comment I assume the intention is to not have `extendSchema` do …
> fix: Don't use extendSchema's validations in buildFederationSchema.

- README.md
- docs/hooks.md
- docs/lifecycle.md
- docsify/sidebar.md
- examples/hooks-gateway.js
- examples/hooks.js
- index.d.ts
- index.js
- lib/errors.js
- lib/gateway.js
- lib/gateway/make-resolver.js
- lib/gateway/service-map.js
- lib/handlers.js
- lib/hooks.js
- lib/subscription.js
- lib/symbols.js
- package.json
- test/gateway/hooks.js
- test/gateway/pollingInterval.js
- test/hooks.js
- test/internals/hookRunner.js
- test/internals/hooksRunner.js
- test/types/index.ts
Closes: https://github.com/mercurius-js/mercurius/issues/380
> Add hooks to Mercurius

- docs/integrations/README.md
- docs/integrations/nexus.md
- docsify/sidebar.md
Some quick adjustments since `@nexus/schema` is now `nexus`.
> docs(nexus): update nexus documentation

- docs/subscriptions.md
- lib/subscription.js
- package.json
- test/subscription.js
This uses the new version of `fastify-websocket` that has support for running hooks before upgrading to websockets inside mercurius, which means things like auth hooks will apply to both http and websocket routes registered by mercurius! Woop! See https://github.com/fastify/fastify-websocket/pull/95 for more details. This also means that custom `verifyClient` functions should be needed less frequently, as you can just rely on `preValidation` hooks wrapping mercurius to apply to all of it.
Only real change I had to made was removing the globally installed websocket handler that replied with an unknown route, which I don't think makes much sense to install anymore now that `fastify-websocket` uses the normal Fastify router and hooks system. 
I think this is semver major though because now …
> Upgrade to fastify-websocket 3.0.0 for plugin encapsulation support

- docs/plugins.md
This PR adds the Mercurius Apollo Registry Plugin to the documented list of available plugins as well as some basic usage.
> docs: Add apollo registry plugin to plugin list

- lib/gateway.js
- lib/gateway/make-resolver.js
- package.json
may resolve #397, or at least the CPU usage issue
This PR changes the id used for the entity resolver caching. It uses the query path instead of the full query object which could be quite heavy to serialize.
> fix: custom entity cache id

- docs/hooks.md
This PR fixes some typos in the hooks documentation as mentioned in this comment: https://github.com/mercurius-js/mercurius/pull/385#discussion_r579053947
> Correct hooks documentation

- index.d.ts
- test/types/index.ts
Adds missing reply type to context. No need to pass it in `context` function, since it's passed already,
Closes #404
> fix(types): missing reply in context

- index.d.ts
- test/types/index.ts
At the moment arg 'schema' is not optional in type 'MercuriusSchemaOptions'. Because of this one gets and error if plugin is registered with 'schema' in options. An example of code which will throw Typescript error:
```
app.register(mercurius, { path: '/' })
app.register(async function (app) {
app.graphql.extendSchema(schema)
})
```
You can also see the Typescript error in included test.
The code works as expected. Seems like typings are incorrect.
> fix(types): mark 'schema' optional in 'MercuriusSchemaOptions'

- lib/gateway.js
- lib/gateway/service-map.js
- tap-snapshots/test-gateway-remote-services.js-TAP.test.js
- test/gateway/remote-services.js
Adds some additional error messaging for gateways that are configured to consume remote services. Previously, if a gateway loaded a remote service and that service had an invalid schema, the gateway would attempt to build a federated schema  and the result of that is a GQL parsing error: `Syntax Error: Unexpected <EOF>.`. 
This pull request adds an additional check before attempting to build the federated schema. If there are no valid SDLs that have been provided to the gateway, we inform the user that this is the case. 
I also added a couple of tests that check the error handling behaviour of a gateway that is consuming remote services.
This is probably more useful for development, but I though this messaging might help other developers locate similar issues faster than it took me!
> fix: improve error messaging for gateway

- docs/api/options.md
- lib/gateway/request.js
This PR extends the options available for the gateway services clients (undici) and the documentation.
> feat(gateway): extend undici agent options

- docs/federation.md
- lib/gateway.js
- lib/gateway/make-resolver.js
- lib/gateway/request.js
- lib/gateway/service-map.js
- test/gateway/rewrite-headers.js
Fix #431 
On gateway setups, query `context` was not being exposed to `rewriteHeaders`.
This PR fixes the issue by passing the `context` to every call to `serviceDefinition.sendRequest` which then exposes it to `rewriteHeaders` as an additional parameter.
> Access context in rewriteHeaders

- docs/hooks.md
- examples/hooks-gateway.js
- index.d.ts
- index.js
- lib/handlers.js
- lib/hooks.js
- test/gateway/application-hooks.js
- test/gateway/hooks.js
- test/gateway/rewrite-headers.js
- test/hooks.js
- test/types/index.ts
This PR adds a new application lifecycle hook as a result of this discussion in Mercurius Auth: https://github.com/mercurius-js/auth/pull/3#discussion_r615405536
It adds the following:
- Add `onGatewayReplaceSchema` application lifecycle hook
- Fixes an issue where the `preExecution` hook was not run when the query has been jit'd. I found this when improving the performance in the Mercurius Auth benchmarks
It also includes a fix for the slow `rewriteHeaders` tests which were taking ~8s to run. I've noticed that `pollingInterval` and `remote-services` tests also take a long time. Looking at the code, I think it's to do with the way the gateway is closed when it errors upon building the schema - however I need to confirm this. Very happy to take a long at this in a follow up PR when I have …
> Add support for Mercurius auth plugin

- docs/plugins.md
- docsify/sidebar.md
This PR adds the doc links for the `mercurius-auth` plugin. Have tested locally, and all looks okay from a docs generation point of view:
> Add Mercurius auth plugin documentation links

- index.d.ts
- test/types/index.ts
Follow-up of https://github.com/mercurius-js/mercurius/pull/454. Added the respective typing to `rewriteHeaders`.
> fix(types): add context to rewrite headers

- lib/gateway.js
- test/gateway/pollingInterval.js
- test/gateway/remote-services.js
- test/subscription-connection.js
Fixes: https://github.com/mercurius-js/mercurius/issues/476
The intermittent `pollingInterval.js` failures include two fixes:
- One to prevent a race condition on Windows when writing a `connection_init` and `start` at the same time.
- One to prevent a race condition on Windows where the mutation was called before the subscription was created.
For reducing the time taken for the `remote-services.js` test to run, I was wasn't able to work out a test case for this without a large code refactor. I've added a timeout for this test to capture the fact that the service connections are now being cleaned up correctly - let me know if you have any ideas on this! :)
I've run the tests on repeat ~60x and found no failures, so am fairly confident this catches the intermittent failures.
> Improve test stability

- lib/gateway.js
- test/gateway/subscription.js
Allows using plain scalars in subscriptions in federation gateway instead of having to wrap them in types
Closes #370
> fix: allow scalar subscriptions in gateway

- lib/gateway.js
- test/gateway/value-types.js
Hi,
I realized that the current valueTypes implementation is fundamentally flawed, for example, "top-level" value types were not handled properly. When a mutation/query/subscription returns a value type, it throws `Cannot return null for Mutation.myMutation`.
Hence, I refactored the way the `defineResolvers` function handles non-scalar types.  I added the documentation in-line. It basically uses `serviceForFieldType` and `serviceForType` to derive whether the field should be resolved from the parent, through a query / subscription / mutation or through an entity query.
#499
> refactor(gateway): defineResolvers now properly handles value types

- index.js
- lib/subscription-connection.js
- lib/symbols.js
- test/loaders.js
This PR actually reverts the previous one a bit. The issue before was that if we defined loaders, they weren't passed into subscriptions. This made it so even if we passed through all the required data it would throw an error and overwrite the data given with null.
Now that we have loaders being passed in that isn't a possibility. I tried to force the issue in some tests and do some cheeky stuff like passing `undefined` as a loader but it would error long before getting through loader definition.
> Subscription loaders

- index.js
- lib/hooks.js
- lib/routes.js
- lib/subscription.js
- test/routes.js
Use provided `context` as a target in merging to keep the object prototype.
Resolves: #514
> fix: change context merging behavior

- docs/faq.md
- examples/disable-introspection.js
- test/disable-instrospection.js
I have created an example of how to disable instrospection using the rule from graphql "NoSchemaIntrospectionCustomRule".
And a isolated test that validate the response errors from graphql with the instrospection rule.
#521
> Validate the disable instrospection custom rule

- static/main.js
I was missing the request headers tab so I enabled it again - I think this is in favour of everyone.
> Add GraphiQL request headers tab

- lib/errors.js
- lib/federation.js
- test/gateway/custom-directives.js
This fixes the issue report here: https://github.com/mercurius-js/mercurius/issues/343#issuecomment-900593479
I found another issue with the GraphQL server not closing properly if the federated schema throws for any reason. I'll resolve this in a follow up PR as the change is out of scope for this PR :)
> Fix duplicate custom directives in the gateway schema

- README.md
- package.json
When user installs graphql into their own package.json alongside `mercurius`, they get:
```
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
https://yarnpkg.com/en/docs/selective-version-resolutions
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```
This is a common problem with graphql package. It was previously discussed here for example: https://github.com/MichalLytek/type-graphql/issues/144 
Beware-this is a breaking change. …
> move graphql into peerDependencies

- lib/subscription-connection.js
- test/subscription.js
When developing I noticed that the second argument of my loaders was always `undefined` when being processed by a subscription.
Looks like the fix is just to pass it in when we init the subscription `kLoaders`. That said, maybe there is a good reason for this that I don't know about?
Happy to further iterate on this!
> Add missing context for subscription loaders

- docs/typescript.md
The current example in the docs passes the `mercurius` instance to `mercuriusCodegen` instead of the Fastify instance. This PR fixes the example.
> docs(typescript): fix mercurius-codegen example

- docs/federation.md
- index.d.ts
- test/types/index.ts
Hello!
This PR fixes wrong TypeScript specification for the `errorHandler` option.
By digging in the code I noticed that handler is used in fastify's `setErrorHandler` which does not allow a return type.
The response must be sent to the client using `reply.send`. The only difference with fastify is that the error type can optionally (and most of the times will) include a `errors` array, so I've created a specific exported type.
I've also fixed the example for the federated use-case.
> fix(typescript): Fixed error handling types.

- docs/integrations/type-graphql.md
- adding 2 missing imports. It's more important for `buildSchema` since it's exported by many libraries a function with same name, but with different implementation
- the example doesn't run out of the box because class Recipe has a `specification` field. I am proposing to omit the value in the returned type
> Documentation improvements for type-graphql example

- static/main.js
This PR fixes an issue with graphiql when we try to load it without service workers.
Closes #625
> Fix: Graphiql not working without sw

- docs/loaders.md
- index.js
- test/federation.js
- test/loaders.js
This PR adds support for the `info` object being passed to the loaders.
Each loader function has the signature loader(queries, context).  `queries` is an array of objects and is now defined as `{ obj, params, info }`
Closes #627
> Add info object to loaders

- index.js
- tap-snapshots/test/reply-decorator.js.test.cjs
- test/reply-decorator.js
In an effort to create a new graphql endpoint, I was encountering the following error when registering the following plugin code:
NOTE: the parent app object has loaders defined in a separate module. 
```javascript
'use strict'
const fp = require('fastify-plugin')
const GQL = require('mercurius')
const schema = `
type Query {
msg: String
}
`
const resolvers = {
Query: {
msg
}
}
async function msg(_, args, context) {
return "hello world!"
}
async function plugin(server) {
server.register(async (app) => {
app.register(GQL, {
schema,
defineMutation: true,
resolvers,
path: '/auth'
})
})
}
module.exports = fp(plugin, {
name: 'auth',
dependencies: ['db', 'redis']
})
```
Upon issuing the following request:
```bash
curl 'localhost:5000/auth' -X POST -H 'Content-Type: application/json' --data-raw …
```
> [bugfix]: "Cannot read property 'create' of undefined" with encapsulated app where parent object has loaders defined

- lib/subscription-protocol.js
- test/subscription-connection.js
- test/subscription-protocol.js
Closes https://github.com/mercurius-js/mercurius/issues/629
Let me know if the unit-tests should be structured differently. Or if you want me to extend the PR and add tests for all the message types of `graphql-transport-ws`.
> Fix incorrect message type for GQL_STOP when using graphql-transport-ws

- docs/hooks.md
- index.js
- test/cache.js
From this PR https://github.com/mercurius-js/mercurius/pull/641#discussion_r746538702 we spotted an issue with the cache usage.
The logic here is that it is not possible to use the jit'ed function.
Within this fix, if the developer changes the `document` on a `preExectution` hook, the caching is skipped:
- the modified document does not trigger the function compiling
- the HTTP request does not use any cached query
To avoid cache skipping, we should `print()` the `modifiedDocument` and rely on the `lru` logic as done here:
https://github.com/mercurius-js/mercurius/blob/aa8eaaa0cb84ce662b84cd3b9fb4a6cf29abddb9/index.js#L445
> fix cache usage

- docs/hooks.md
- index.d.ts
- index.js
- lib/handlers.js
- lib/hooks.js
- package.json
- test/hooks.js
- test/types/index.ts
Opening this PR to get some feedback.
I'm working on this issue: https://github.com/mercurius-js/auth/issues/43
The target of that issue is to modify the output schema for inspection queries like so
```js
app.graphql.addHook('preExecution', async function filterHook (schema, document, context) {
// removes those objects that the user has not access to
const filteredSchema = auth.filterDirectives(schema, authSchema)
return {
schema: filteredSchema
}
})
```
The inspection query is a standard query that is being executed on the `app.graphql.schema` object.
To let the user (and in this case the mercurius/auth plugin) change the schema where the query is executed and affect the output results, the `preExecution` hook may manage a schema replacing.
Note that I did not use …
> feat: add modifiedSchema on preExecution hooks

- lib/federation.js
- test/gateway/schema.js
Added a filter on the query extensions in the schema create. 
This filter removes all the _service fields in the extend queries. 
This will help to be compatible with multiple services in gateway mode that do not remove the _service field in the SDL while still supporting federation.
see:
https://github.com/mercurius-js/mercurius/issues/643
> compatibility: schema validation in gateway mode 

- lib/routes.js
- test/errors.js
Fixes https://github.com/mercurius-js/mercurius/issues/677
> Fix regression in handling badly formed JSON

- lib/routes.js
- test/errors.js
This PR extend #678 to include custom context in error formatter.
@mcollina I am not sure if context (custom and/or default) is needed in case when custom error handler has been used (as in is such case error formatter is not called at all with my understanding?)
> Extend regression fix in handling bad json to include custom context

- docs/hooks.md
The `preValidation` hook is not called when queries has been cached in `lru`. I find this quite confusing, maybe this info will help others to avoid some mistakes.
> Clarify `preValidation` documentation

- index.d.ts
- test/types/index.ts
When context is null for example, it crashes with a type error
```
TypeError: Cannot read property 'reply' of null
at AsyncFunction.defaultErrorFormatter (/home/capaj/work-repos/authier-repos/authier/node_modules/mercurius/lib/errors.js:67:19)
```
> fix: specify type better for context arg in defaultErrorFormatter

- docs/api/options.md
- index.d.ts
- index.js
- lib/routes.js
- lib/subscription-connection.js
- lib/subscription.js
- test/subscription.js
Implements the [GQL_CONNECTION_KEEP_ALIVE](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_keep_alive) protocol message in order to keep the socket alive (e.g. useful on Heroku, to prevent H15 errors).
Happy to tweak test cases in case we need more coverage on the interval.
> Implement GQL_CONNECTION_KEEP_ALIVE on subscription server

- docs/api/options.md
Updated the custom error formatter section of the documentation. Related to the question asked in #696.
> docs: update options doc regarding error formatter

- lib/errors.js
- test/hooks.js
Somehow related to this https://github.com/mercurius-js/mercurius/issues/699
> add ErrorWithProps handler for mercurius hook

- index.js
- test/loaders.js
When using `allowBatchedQueries` the loader would get overwritten for each query being processed
which would ultimately prevent the loaders being reuses for the whole batch.
The fix is pretty native, and only overwrittes the reply's loader if not provided if in allowBatchedQueries mode.
The behaviour for non `allowBatchedQueries` should be preserved.
> Fixes issue with batchedQueries overriding loader

- package.json
Only the `@graphql-tools/*` dependencies are used.
```sh-session
$ rg graphql-tools
examples/executable-schema.js
5:const { makeExecutableSchema } = require('@graphql-tools/schema')
package.json
32:    "@graphql-tools/merge": "^8.0.0",
33:    "@graphql-tools/schema": "^8.0.0",
34:    "@graphql-tools/utils": "^8.0.0",
docs/api/options.md
335:const { makeExecutableSchema } = require('@graphql-tools/schema')
test/app-decorator.js
12:const { makeExecutableSchema } = require('@graphql-tools/schema')
test/directives.js
7:const { makeExecutableSchema } = require('@graphql-tools/schema')
8:const { mergeResolvers } = require('@graphql-tools/merge')
15:} = require('@graphql-tools/utils')
test/hooks.js
6:const { mapSchema } = require('@graphql-tools/utils')
test/types/index.ts
12:import { …
```
> chore: remove unused `graphql-tools` dep

- index.d.ts
- test/types/index.ts
From what I can see the [initially suggested signature for defaultErrorFormatter](https://github.com/mercurius-js/mercurius/issues/196) was:
```
(err: Error | GraphQLError | FastifyError) => {
statusCode: number
response: {
data: object
errors: object[]
}
}
```
But somewhere down the line it became:
```
(
execution: ExecutionResult,
context: MercuriusContext
) => { statusCode: number; response: ExecutionResult };
```
However from [the JS code](https://github.com/mercurius-js/mercurius/blob/master/lib/errors.js) I can see that we're testing for [`instanceof ErrorWithProps`](https://github.com/mercurius-js/mercurius/blob/master/lib/errors.js#L46) and [`instanceof GraphQLError`](https://github.com/mercurius-js/mercurius/blob/master/lib/errors.js#L59) - both subclassed from `Error`.
This PR …
> fix: typings for defaultErrorFormatter

- lib/gateway.js
- lib/gateway/make-resolver.js
- test/gateway/type-redefined.js
> [gateway] Resolve nested references in a value type resolved from a top-level resolver

- package.json
This resolves a peer dependency warning for graphql@16.
(I realise it's in semver range, but forcing the update so the dependency tree is guaranteed to be valid also after aggressive deduplication makes sense)
> fix: update graphql-jit

- index.d.ts
- test/types/index.ts
Hello! I started looking into using Mercurius as a gateway and I noticed that the typescript interface was missing two fields that were recently added.
This PR adds `retryServicesCount` and `retryServicesInterval` in the MercuriusGatewayOptions interface.
> add missing types for retry services options

- .github/workflows/backport.yml
- docs/development.md
- docsify/sidebar.md
As titled!
From the updated docs: 
As soon as one opens a PR against the default branch, and the change should be backported to `v8.x`, you should add the corresponding backport label. For example, if we need to backport something to `v8.x`, we add the following label:
- `backport v8.x`
And you are done! If there are no conflicts, the action will open a separate PR with the backport for review.
If the PR can't be automatically backported, the GitHub bot will comment the failure on the PR.
> Add backport GitHub action

- lib/gateway/make-resolver.js
- test/gateway/with-references-in-unions.js
Fixes: https://github.com/mercurius-js/mercurius/issues/751
> Correctly handle reference types at the same path in the gateway

- docs/api/options.md
Adds information about the new `service.agent` option added in #749
> Document new `service.agent` configuration option.

- lib/federation.js
- test/gateway/custom-directives-with-batching.js
- test/gateway/custom-directives.js
- test/gateway/pollingInterval.js
- test/gateway/requires-directive.js
> Keep requires directive in gateway schema

- static/main.js
Fixes https://github.com/mercurius-js/mercurius/issues/771
unpkg is not setting up correct cross origin headers causing browsers to block scripts and styles loaded from them. The proposed change tells the browser to load the content from unpkg.
**How to test the fix**
1. Create a test server ([gist here](https://gist.github.com/conradthegray/16751dd0870376e366d82280b92da265))
2. Run the test server and navigate to `http://localhost:3000/graphiql`
3. You should see a blank page without the fix applied
4. Apply the fix in `mercurius-771/node_modules/mercurius/static/main.js` file
5. Reload the test server and navigate to `http://localhost:3000/graphiql`
6. You should see GraphiQL interface
> fix: allow cross origin loading for graphiql

- index.js
- test/gateway/config.js
Fixes #787 
Checks that the `services` passed to `gateway` option are matching what is documented (in the docs and in TS types) and used so far:
1. `services` should have a unique (String) `name` 
2. `services` should have one or multiple (as an Array) `url` that is of type `String`
Given the current `gateway` `services` option is really permissive and this PR restricts it, this may be considered as a BREAKING CHANGE, but given TS types explicitly restrains the options to what is implemented by this PR, we might want not to consider it breaking... WDYT ?
> fix: gateway configuration validation

- index.d.ts
This PR fixes a typo `lifeycle` -> `lifecycle`.
> chore: fix typo

- index.js
- lib/persistedQueryDefaults.js
When using Mercurius with a module bundler such as esbuild or webpack, running will output `TypeError: LRU is not a function`.
Not sure what originates the error, but it has already been fixed in fastify (see https://github.com/fastify/fastify/pull/2918).
> Fix LRU require for module bundlers

- lib/subscription-connection.js
- test/subscription-connection.js
Always clear `SubscriptionConnection.subscriptionContexts` and `SubscriptionConnection.subscriptionIters` after a subscription completes, instead of waiting for the client to send a `complete` message.
This prevents buggy clients from leaking memory on the server.
> Always teardown subscriptions on completion

- package.json
- test/gateway/retry-failed-services.js
I still believe fake-timers are the main issue behind this. There are still some other tests being flaky due to fake timers tickAsync. I opened a pull request to discuss a potential solution.
Steps I've taken:
- Understand multiple tests were contradicting each other due to the same port number
- Run the test couple of times, it was still flaky
- Updated sinon fake timers and tap, since the only ambigious side of the test was the fake timers.
- Found the following issue: https://github.com/tapjs/node-tap/issues/709
- Changed for loop 10 times tickAsync(1000) with for loop 100 times with tickAsync(100). Which solved the issue on the retry-failed-services.js test.
> fix: handle flaky tests

- test/gateway/application-hooks.js
- test/gateway/pollingInterval.js
- test/gateway/retry-failed-services.js
- test/gateway/value-types.js
- test/subscription.js
This pull requests properly clears native timers on the installation of sinon/fake-timers.
> fix: clear native timers on tests

- static/main.js
- static/sw.js
The graphiql version used by Mercurius was pretty old. Version 2 recently came out which has a lot of improvements.
I have verified this in my own project and it appears to work properly.
> feat: update to GraphiQL to version 2.0.2

- index.d.ts
- lib/routes.js
- test/batched.js
- test/options.js
- test/subscription-connection.js
- test/types/index.ts
resolves #842
Fixes `context.__currentQuery` being overwritten by subsequent batched query operations.
Stores `context.operationsCount` and `context.operationId` (same naming as with subscriptions) to uniquely identify batched query operations at a later stage.
> feat: uniquely identify batched queries

- README.md
- bench/gateway-service-1.js
- bench/gateway-service-2.js
- bench/gateway.js
- bench/standalone.js
- docs/api/options.md
- docs/federation.md
- docs/integrations/nexus.md
- docs/integrations/open-telemetry.md
- docs/integrations/prisma.md
- docs/integrations/type-graphql.md
- docs/plugins.md
- examples/basic.js
- examples/custom-http-behaviour.js
- examples/disable-introspection.js
- examples/executable-schema.js
- examples/full-ws-transport.js
- examples/gateway-subscription.js
- examples/gateway.js
- examples/hooks-gateway.js
- examples/hooks-subscription.js
- examples/hooks.js
- examples/loaders.js
- examples/persisted-queries/index.js
- examples/playground.js
- examples/subscription/mqemitter-mongodb-subscription.js
- test/types/index.ts
The documentation references `.listen(<port>)` in several places, but this variadic function is deprecated in Fastify v4 and throws this warning:
> (node:254) [FSTDEP011] FastifyDeprecation: Variadic listen method is deprecated. Please use ".listen(optionsObject)" instead. The variadic signature will be removed in `fastify@5`.
Since the current `package.json` requires Fastify v4+, this should be safe to do: https://github.com/mercurius-js/mercurius/blob/bbb8b269344f04ad9a50ae9210c69d31761ab6a7/package.json#L44
Deprecation guide: https://github.com/fastify/fastify/blob/2fd918298d55aaab74585c0b71081ad40988b280/docs/Guides/Migration-Guide-V4.md#deprecation-of-variadic-listen-signature
> docs: replace uses of variadic `.listen` function

- index.d.ts
The existing types for the `jit` property were misleading. The value defaults to `0`, which means that queries will not be `jit`-ed.
https://github.com/mercurius-js/mercurius/blob/bbb8b269344f04ad9a50ae9210c69d31761ab6a7/index.js#L80
Here's the code that determines if `jit` should happen:
https://github.com/mercurius-js/mercurius/blob/bbb8b269344f04ad9a50ae9210c69d31761ab6a7/index.js#L613
On the first request, `cache` is `undefined`, so `jit` does not occur:
Then, on subsequent requests, the request count is `1`, so again `jit` does not occur:
> fix(types): correct `jit` default value

- lib/gateway/make-resolver.js
- test/gateway/resolver-key-handle-digits.js
> fix: as gateway resolver key should handle digits (#880)

- index.d.ts
- test/types/index.ts
This PR extends the return types of `subscription.onConnect` to include `boolean` type
The docs mention:
> subscription.onConnect: Function A function which can be used to validate the connection_init payload. If defined it should return a **truthy value** to authorize the connection. If it returns an object the subscription context will be extended with the returned object.
closes #871 
cc @simoneb
> Fix: subscription.onConnect types

- index.js
- lib/gateway.js
- lib/gateway/build-gateway.js
- package.json
- test/gateway/config.js
Cleanup of the index file.
the stuff related to the gateway are moved in a separate file and the initialization is done with:
```
let gateway
let lruGatewayResolvers
if (opts.gateway) {
lruGatewayResolvers = buildCache(opts)
gateway = await initGateway(opts, fastifyGraphQl, app)
schema = gateway.schema
}
```
Further improvement are required but this is the first step required for the gateway extraction.
@simoneb @mcollina
> Clean up index.js file from gateway init instructions #887

- examples/subscription/memory.js
- static/main.js
- static/sw.js
> Update GraphiQL to v2.0.9

- docs/subscriptions.md
- lib/subscription-connection.js
- lib/subscription.js
- test/subscription.js
This PR does a few things:
1. uses the real `Request` object in the subscription `Context`. Reply is still "faked" as there is no `Reply` for websockets.
2. copies over all the data incoming as part of `connection_init` packet to `req.headers`. If there is a `headers` object that's used instead (as it was before). This change was needed because GraphiQL treats all the payload as headers.
> Use the real Request object in subscriptions

- lib/gateway/build-gateway.js
- test/gateway/schema.js
While using external graphs, they often (if not always) don't have any space around SDL, so while joining the strings, without adding any additional space, create unexpected keywords and throw errors while trying to parse the schema.
> Add space between merged SDLs to fix merging errors

- docs/api/options.md
I think that's a good thing to mention that JIT is disabled by default and should be explicitly enabled to get the performance benefits. I personally thought that it's enabled by default, but then I started digging into Mercurius and found how JIT is actually used there, and that it's not enabled by default.
Screenshot of the updated docs:
> Explicitly say in the docs that JIT is disabled by default

- index.d.ts
- test/types/index.ts
Adds the type definition for the configuration of graphiql using an object.
> feat: add types for object in graphiql configuration

- lib/federation.js
- test/federation.js
This fix prevents the app from breaking if schema contains [directives imports](https://www.apollographql.com/docs/federation/federated-types/federated-directives/#importing-directives) like this:
```gql
extend schema
@link(url: "https://specs.apollo.dev/federation/v2.0",
import: ["@key", "@shareable"])
```
I'm not sure if those imports actually work with Mercurius, but are a valid syntax, so shouldn't break it.
> Prevent parsing schema exceptions when importing directives 

- lib/subscription-connection.js
- package.json
from issue https://github.com/mercurius-js/mercurius/issues/725.
events.on is native on node since added in: v13.6.0, v12.16.0 so I think there is no reason to keep this polyfill for 10.x
> refactor: removed events.on and use native api

- docs/hooks.md
- index.d.ts
- index.js
- lib/handlers.js
- lib/hooks.js
- test/hooks.js
- test/types/index.ts
I saw discussions about this on https://github.com/mercurius-js/mercurius/issues/876, which mainly talked about **accessing** variables, but there is a comment that also mentions updating them.
I require this use-case, where hooks can modify the incoming variables based on logic or contacting external systems. See the test included with the PR for an example. 
This could have be achieved by putting the logic in a plugin earlier in the chain than Mercurius, but preventing double query parsing would be difficult, as the hooks need to be query-aware. 
I'll admit I don't have a complete understanding of this codebase so forgive me if there are any things I've missed here, it's mainly to frame the requirement I have and start a discussion. 
If there is any modifications you'd like here, let me …
> feat: Allow preExecution hook to modify variables

- index.js
- test/app-decorator.js
closes #804 
JSON ast can be now used as input.
The change can be tested with the code of the test added at test/app-decorator.js
Comments are welcomed for both performance and security on the use of `JSON.parse` function
It should be decided whether this feature is desired.
> feat: ast input support added

- docs/integrations/nestjs.md
Hi,
I updated the link for the support server for NestJS because the link that is there now is invalid.
NestJS discord server: https://discord.com/invite/G7Qnnhy
P.s. Thank you for creating Mercurius
> docs(): fix link for discord server nestjs

- docs/hooks.md
- examples/hooks-subscription.js
- index.d.ts
- lib/hooks.js
- lib/subscription-connection.js
- test/subscription-hooks.js
- test/types/index.ts
This is related to #959, it will be needed in the gateway to identify when a subscription has ended and which subscription was that.
> feat: include subscription id in onSubscriptionEnd hook

- lib/routes.js
- lib/subscription-connection.js
- lib/subscription.js
- test/errors.js
- test/subscription.js
RE: https://github.com/mercurius-js/mercurius/issues/966
Currently, if there are graphql errors returned from a subscription in the standard "errors" property on a response - these do not get the opportunity to be passed through the potentially provided `errorFormatter`. This means any formatting and any side effects you may have in the error formatter are not run for these cases.
This PR applies the provided error formatter or merely the default error formatter as a fallback. 
NOTE:
I'm not 100% convinced on this change as is, my main thing is that in the case of mutation/query, we get to override the status code for the response in addition to the main payload. This doesn't apply to subscriptions and therefore that is thrown away in that case. It will work, but semantically _**may**_ be …
> Use error formatter for subscription GQL errors

- docs/faq.md
- examples/schema-by-http-header.js
closes #913 
This PR explains exposing two different mercurius instances to the same route using the fastify/find-my-way custom constraints.
> Docs: document schema by http header (#913)

- index.js
- tap-snapshots/test/routes.js.test.cjs
- test/routes.js
Fixes issue where mutations are not allowed over web sockets (subscriptions).
See: https://github.com/mercurius-js/mercurius/discussions/977
> fix mutation over websocket/subscription

- package.json
Updates to `@fastify/websocket` v8 to address a leak and crash in certain condition. This requires a minimum version of Fastify of v4.16.0 (just released), hence the major update.
> Update to @fastify/websocket v8

- docs/custom-directive.md
Improve documentation for custom directives with Federation
Close: mercurius-js/mercurius-federation#28
> docs: improve custom directives doc with federation

- index.html
This allows for https://mercurius.dev to offer a richer preview when shared in platforms like Discord or the usual social networks.
> add meta tags for page previews

- lib/subscriber.js
- test/subscriber.js
This patch calls the removeListener on emitter for all subscribed topics. It is important to avoid memory leak.
When using MQEmitterRedis is most important to unsubscribe pattern on redis server.
> Remove all listeners on close

- static/main.js
fix - https://github.com/mercurius-js/mercurius/issues/1003 issue. 
The graphiql failed to load schema when it's been deployed on https://foo.com/bar/graphiql, it will look for the schema at https://foo.com/graphql but it's actually running on https://foo.com/bar/graphql, which is an invalid graphql endpoint as it is missing window.baseUrl. So we are addressing this in the PR. 
Thank you @ddai1  for help here.
> make url dynamic so even if the graphiql is deployed on baseUrl it can work.

- static/main.js
- test.js
bugfix:
- The `window.baseurl` is not working as expected as in some cases window.baseurl is undefined. 
- using `window.location.pathname` is better then using `window.baseurl` as in some cases the value is undefined.
> bugfix: window.baseurl is not working in all the cases to fix this using window.location.pathname

- static/main.js
- remove the extra slash which is not required.
> bugfix: remove the extraa slash

- docs/api/options.md
- index.d.ts
- index.js
- test/graphql-option-override.js
Support passing options to GraphQL's `validate` and `parse` functions.
Reasoning to allow configuration of these functions topics is fine tuning to prevent DDOS attacks.
This allows developers to set:
1. `validate`'s options of `maxErrors` to something more/less than the 100 default. This prevents an attacker from specifying 100 invalid fields, requiring CPU time generating validation errors.
2. `parse`'s options of `maxTokens` to a value. It has no default. This prevent an attacker from producing a overly high complexity query that requires a high amount of CPU time.
> feat: support passing options to graphql validate and parse

- index.d.ts
- index.js
- test/types/index.ts
Closes: #1047 
- I have taken the code as is (to de-risk) and just moved the root level types into the declared namespace, other key bits are detailed as follows:
```typescript
type Mercurius = typeof mercurius
declare namespace mercurius {
// ...
export const mercurius: Mercurius
export { mercurius as default }
}
declare module "fastify" {
// ...
}
declare function mercurius
(
instance: FastifyInstance,
opts: mercurius.MercuriusOptions
): void;
export = mercurius;
```
- All the types tests pass and have added some other tests where needed
- Have taken some inspiration from the fastify repo and other plugins for consistency
- Have also tested against this repo and all appears to be okay: https://github.com/iamchathu/mercurius-ts-example
> Support nodenext

- docs/api/options.md
- index.d.ts
- index.js
- lib/routes.js
- test/routes.js
- test/types/index.ts
ability to add and modify route properties to modify how the routes might behave. One example is to be able to create a schema split which https://github.com/nearform/mercurius-dynamic-schema/ tries to achieve. 
Helps close https://github.com/nearform/mercurius-dynamic-schema/issues/4
> Feat: add the ability to add in additional route properties

- package.json
```
undici  <=5.28.2
Undici proxy-authorization header not cleared on cross-origin redirect in fetch - https://github.com/advisories/GHSA-3787-6prv-h9w3
```
> fix: undici security vulnerabilities

- package.json
Updates undici to keep up with latest security related release of the 5.x.x. version branch, see [undici release info](https://github.com/nodejs/undici/releases/tag/v5.28.4) for more information.
npm audit output:
```
undici  <=5.28.3
Undici's Proxy-Authorization header not cleared on cross-origin redirect for dispatch, request, stream, pipeline - https://github.com/advisories/GHSA-m4v8-wqvr-p9f7
Undici's fetch with integrity option is too lax when algorithm is specified but hash value is in incorrect - https://github.com/advisories/GHSA-9qxr-qj54-h672
```
> fix: updates undici to keep up with latest security release

- lib/errors.js
- test/errors.js
fixes #1024
* Current unit test handle coverage so no test was added
* Fix: Check that `error.orginialError.errors` is an `Array`
> fix: handle if error.originalError.errors is not array

- lib/subscription-connection.js
- test/subscription-connection.js
- test/subscription-hooks.js
- test/subscription.js
The graphql-ws protocol specifies that the payload of an `'error'` message should be an array of GraphQL errors. ([ref](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#error))
To accommodate this, I created the sendError function to manage the transformation and updated all related tests accordingly.
> Error through subscription wrapped in an array

- static/main.js
- static/sw.js
Updated the graphiql and react versions to how they're used in the official graphiql example([link](https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html) for reference) for the same.
Because of hard locking graphiql was locked to version 2.0.9 when the latest stable graphiql version is 3.7.1. The graphiql version 3.7.1 seems to work without issues with mercurius. React follows semantic versioning so no point in hard locking it to a patch version. 
Update: Restored hard locking, versions are hard locked to the latest stable versions
> updated graphiql and react to the latest stable versions

- docs/api/options.md
- index.d.ts
- lib/errors.js
- lib/persistedQueryDefaults.js
- lib/routes.js
- test/persisted.js
Closes #1123 
While updating tests I noticed that the behavior I'm "fixing" was explicitely tested, so presumably desired. I haven't found any references of this on Apollo Server APQ flow, but now I'm unsure if this should be considered a Breaking Change or not.
> feat: APQ should persist queries only when inside an APQ flow

- index.d.ts
- test/types/index.ts
While implementing a custom PersistedQueryProvider, we noticed that the types were not correct for the "getQueryFromHash" function. In fact, the function may return undefined if the query does not exist, but as of now the types do not allow that.
This PR fixes this (small) issue.
> feat: improve PersistedQueryProvider types

- index.d.ts
- test/types/index.ts
The rationale is that mercurius implicitly injects the `pubsub` field into the context received by the graphql resolvers. For making the context type-safe we need to define a custom context type to annotate its typescript type correctly for usage in the graphql resolvers and its in that context type where we can annotate the typescript type for `pubsub` object correctly for usage in the graphql resolvers by having the option of providing strict `event_name-payload` types to the `pubsub.subscribe` and `pubsub.publish` methods.
Usage is shown in the `example.ts` file present in the root directory of [this](https://stackblitz.com/~/github.com/mercurius-js/mercurius) stackblitz example with proper comments.
This implementation is inspired by …
> made mercurius's implicitly injected pubsub subscribe/publish methods type safe

- static/main.js
- static/sw.js
Updated URLs in the service worker to use GraphiQL v3.8.3.
Ensures latest UI fixes & compatibility improvements.
> simple(graphiql): bump GraphiQL version to 3.8.3

- docs/subscriptions.md
- index.d.ts
- lib/subscriber.js
- test/subscription.js
- test/types/index.ts
This PR wants to add the capability to have custom params on `subscribe` method using a `CustomPubSub` implementation. This is useful in case you need to get an argument from the subscription method
> feat: custom pubsub with custom args on subscribe method

- test/reply-decorator.test.js
Proposals:
- migrated `reply-decorator.test.js` from `tap` to `node:test` 🔥
> test: migrated reply-decorator.test.js from tap to node:test

- test/persisted.test.js
Proposals:
- migrated `persisted.test.js` from `tap` to `node:test` 🔥
> test: migrated persisted.test.js from tap to node:test

- test/loaders.test.js
Proposals:
- migrated `loaders.test.js` from `tap` to `node:test` 🔥
> test: migrated loaders.test.js from tap to node:test

- test/validation-rules.test.js
Proposals:
- migrated `validation-rules.test.js ` from `tap` to `node:test` 🔥
> test: migrated validation-rules.test.js from tap to node:test

- test/cache.test.js
Proposals:
- migrated `cache.test.js` from `tap` to `node:test` 🔥
> test: migrated cache.test.js from tap to node:test

- test/aliases.test.js
Proposals:
- migrated `alieses.test.js` from `tap` to `node:test` 🔥
> test: migrated alieses.test.js from tap to node:test

- lib/routes.js
- static/main.js
- test/routes.js
Fixed a typo in GraphiQL plugin variable names throughout the codebase. The variable name was incorrectly spelled as `GRAPIHQL_PLUGIN_` instead of `GRAPHIQL_PLUGIN_`.
This typo was preventing GraphiQL plugins from loading correctly in the browser interface. When users configured GraphiQL plugins via the `ide.plugins` option, the plugins **would** fail to initialize because the JavaScript code was looking for incorrectly named global variables.
- **lib/routes.js**
- **static/main.js**
- **test/routes.js**
- ✅ All existing tests pass (691 assertions, 0 failures)
- ✅ TypeScript compilation successful
- ✅ Linting passes with no errors
- ✅ No breaking changes introduced
> fix: correct GraphiQL plugin variable names

- test/errors.js
- test/internals/hooks-runner.test.js
Proposals:
- migrated `hooks-runner.test.js` from `tap` to `node:test` 🔥
- renamed file in `kebab-case` 🔥
- fixed problem with `errors.js` test 🔥 ( Fix Pipeline CI )
> test: migrated hooks-runner.test.js from tap to node:test
