README.md, index.js, package.json, test/app-decorator.js
Fixes https://github.com/mcollina/fastify-gql/issues/3
=> Add support for makeSchemaExecutable

index.js, tap-snapshots/test-routes.js-TAP.test.js, test/routes.js
=> Add support for execution errors

README.md, index.js, test/app-decorator.js
This is a proposition to solve #25
=> Add defineMutation option

index.js, test/app-decorator.js
This PR adds support for union and interface, and related tests !
=> feat: add union and interface support

README.md
updated the documentation to describe how to access the request object using context in a resolver
fixes - https://github.com/mcollina/fastify-gql/issues/33
=> updated the documentation to describe how to access the request object

index.js, test/app-decorator.js, test/loaders.js
added app to the context argument in loaders
=> add app to loaders context

index.d.ts, index.js, package.json, test/types/index.ts, test/types/tsconfig.json
This PR adds Typescript typings.
=> feat: add typings

README.md, index.d.ts, index.js, routes.js, test/routes.js
This PR is the same as stated in #74 and addresses the review comments.
Closes #74 
Closes #71
=> Add custom GraphQL context option

lib/subscriber.js, package.json
Use node streams package instead
=> Remove readable-stream dependency

static/playground.html
In order to work with subscriptions playground needs additional endpoint.
=> Add subscription endpoint to playground

README.md, index.d.ts, index.js, test/app-decorator.js
This PR closes #100 
`replaceSchema` works great with `makeSchemaExecutable`
=> feat: add .replaceSchema method

README.md, lib/routes.js, test/routes.js
=> Add application/graphql support

index.js, lib/routes.js, tap-snapshots/test-routes.js-TAP.test.js, test/routes.js
=> Fix: Incorrect Graphql Errors processing

lib/subscriber.js, lib/subscription.js, package.json
This fixes a regression on Node v13
=> Use readable-stream to have a stable stream implementation

lib/routes.js, static/graphiql.html, static/main.js, test/routes.js
=> Serve .js files when ide is enabled

examples/gateway.js, lib/routes.js, static/graphiql.html, static/main.js, static/playground.html, tap-snapshots/test-routes.js-TAP.test.js, test/routes.js
=> Initialise Playground with correct GraphQL endpoint

index.d.ts
=> Add IResolver type to type definition

test/gateway/methods.js, test/gateway/request.js, test/gateway/schema.js
This PR fixes the slow running tests:
Closes #146
=> Fix slow tests

lib/routes.js, test/routes.js
I found this typo by accident and thought it would be nice to create a PR to fix it :)
=> fix: typo in reply

index.d.ts
=> Add Request interface 

examples/gateway.js, index.js, lib/errors.js, lib/gateway/request.js, lib/routes.js, test/errors.js, test/routes.js
=> fix(gateway): propagate errors from sub-services in gateway mode

README.md, index.d.ts, index.js, lib/routes.js, test/batched.js
=> Add Support For Batched Queries

index.js, package.json, test/app-decorator.js
This will help with https://github.com/mcollina/fastify-gql/issues/215.
=> Provide a better error message for bad schemas

index.js, lib/errors.js, lib/routes.js, test/errors.js
=> Add and fix test case for error formatting with JIT enabled

index.d.ts, test/types/index.ts
`verifyClient` following [@types/ws](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ws) and [fastify-websocket types](https://github.com/fastify/fastify-websocket/blob/master/index.d.ts)
=> improve subscription types + tests

lib/queryDepth.js, test/query-depth.js
- Fixed query depth calculation (length of flat fields list (not only depth) and fields order were matter in calculation)
- Added current query depth to error message
- Fixed tests
=> fix query depth calculation

test/gateway/pollingInterval.js
=> Fix :: Gateway :: Slow test: test/gateway/pollingInterval.js

lib/subscription-connection.js, lib/subscription.js, test/subscription-connection.js, test/subscription.js
This PR is just a draft for a failing test that shows the async subscription context bug.
It basically the same as the existing test for custom context, but with an artificial delay simulating a common http request delay.
EDIT: Added fix.
Fixes #235
Fixes #208
=> Fix async subscription context

index.js, tap-snapshots/test-errors.js-TAP.test.js, tap-snapshots/test-routes.js-TAP.test.js, test/errors.js
Fixes https://github.com/fastify/help/issues/227
=> Fix inconsistency in handling errors

test/subscription.js
Replacing `wait` calls with `tickAsync` from `FakeTimers`.
The issue doesn't have much description at the moment and it's possible that you had a different idea to achieve this. If that's the case, I'll be glad to get the feedback and change it accordingly.
Thanks!
=> Switch to fake timers for test/subscription.js (#243)

examples/subscription/mqemitter-mongodb-subscription.js
starting with the mongodb example, trying something a bit different
=> add mqemitter mongodb subscription example (#81)

README.md, index.js, lib/routes.js, tap-snapshots/test-routes.js-TAP.test.js, test/routes.js
fixed [272](https://github.com/mcollina/fastify-gql/issues/272)
this RP is WIP, its missing documentation and testing (I'm not sure how to test it)
but I want to make sure I got the settings option name right.
=> add playground settings option

docs/protocol-extension.md, lib/gateway/make-resolver.js, lib/subscription-client.js, lib/subscription-connection.js, test/gateway/connectionInit-extension.js, test/gateway/subscription.js, test/subscription-client.js, test/subscription-connection.js, test/subscription.js
This PR is an implementation of the solution proposed in #268 that should solve the `connection_init` handshake issue.
=> feat: GraphQL over WebSocket protocol extensions and 'connectionInit' extension

index.d.ts
=> Add `playgroundSettings` to Typescript types.

lib/gateway/make-resolver.js, test/gateway/schema.js
Missing 'schema' parameter inside recursive, this cause error: 
> Cannot read property 'getType' of undefined
=> Fix nested fragment bug

lib/gateway/make-resolver.js, test/gateway/schema.js
=> fix(gateway): should not throw on nullable reference

lib/gateway/make-resolver.js, test/gateway/schema.js
The gateway doesn't handle InlineFragment properly
=> fix(gateway): handle InlineFragment

lib/gateway.js, lib/gateway/make-resolver.js, test/gateway/schema.js
The gateway doesn't handle external array references properly
=> fix(gateway): support array references

README.md
Reference: https://github.com/mercurius-js/mercurius/pull/280#issuecomment-700358125﻿
=> doc(README): add note about errorHandler

README.md, docs/protocol-extension.md, examples/basic.js, examples/gateway-subscription.js, examples/gateway.js, examples/loaders.js, examples/persisted-queries/index.js, examples/subscription/mqemitter-mongodb-subscription.js, index.d.ts, index.js, package.json, test/plugin-definition.js, test/types/index.ts
renamed to mercurius! Let me know if I missed anything
=> Rename to mercurius

lib/routes.js, test/routes.js
This PR allows to use automatic persisted queries using GET requests.
=> feat: support extensions from query for GET requests

index.js, tap-snapshots/test-routes.js-TAP.test.js, test/gateway/config.js, test/gateway/methods.js
I noticed odd wording in one of the error messages which lead to few other places too.
I updated the messages based on my best judgement, the changes are open for debate if there is a disagreement.
=> Improve error messages

lib/gateway/make-resolver.js, test/gateway/schema.js
#313 introduced an issue with union and inlineFragments, this PR reintroduce the check on `getFields`
=> fix(gateway): handle union and inlineFragments

docs/nexus-schema.md
An example of Nexus schema with this plugin #297
=> Add documentation regarding Nexus schema

docs/api/options.md, index.d.ts, index.js, test/directives.js, test/federation.js, test/types/index.ts
This is my second take on simpler api for custom directives.
=> Add support for simplified api for custom directives

docs/api/options.md, docs/federation.md
Noticed few inconsistencies in gateway docs and added missing `mandatory` opt in docs.
=> Update gateway "mandatory" opt docs

README.md, docs/api/options.md, package.json, test/app-decorator.js, test/directives.js, test/types/index.ts
Not a big deal but can save some bytes in the install scripts.
Also changed the docs as it's a better practice
=> Move to graphql-tools scope packages

docs/integrations/README.md
Very minor fix of links in integrations index
=> fix integrations links for in-github navigation

lib/gateway/make-resolver.js, test/gateway/extends-directive.js
Fixes: https://github.com/mercurius-js/mercurius/issues/353
=> fix(gateway): arguments not passed to fields on reference types

lib/gateway/make-resolver.js, test/gateway/extends-directive.js
fixes: https://github.com/mercurius-js/mercurius/issues/356
=> fix: gateway doesn't strip non-service types when querying with inline fragments

.github/workflows/ci.yml, .gitignore, lib/routes.js
> also added all the different lockfiles options to the .gitignore
=> add mac & windows ci workflows, replace eol with lf

index.d.ts, test/types/index.ts
#371 had onDisconnect loosely typed, this is a very small fix, also added it's usage in the typescript test
=> improve onDisconnect types

README.md
=> docs: copyedit README.md

lib/gateway.js, test/gateway/pollingInterval.js
=> fix(gateway/refresh): set typeToServiceMap Query, Mutation and Subscription properties to null

lib/subscription-connection.js, test/subscription-connection.js
=> Call return on subscription resolver async iterator

test/app-decorator.js, test/gateway/connectionInit-extension.js, test/gateway/extends-directive.js, test/gateway/hooks.js, test/gateway/methods.js, test/gateway/pollingInterval.js, test/gateway/request.js, test/gateway/requires-directive.js, test/gateway/schema.js, test/gateway/subscription.js, test/subscription.js
Fixes: https://github.com/mercurius-js/mercurius/issues/394
=> Fix intermittent test failures

index.js, test/app-decorator.js
=> fix: disabling cache breaks replaceSchema

README.md
=> Fix CI badge url

docs/hooks.md, docs/lifecycle.md, examples/hooks-subscription.js, index.d.ts, lib/gateway/make-resolver.js, lib/handlers.js, lib/hooks.js, lib/subscription-connection.js, lib/subscription.js, test/gateway/subscription-hooks.js, test/subscription-hooks.js, test/types/index.ts
Closes: https://github.com/mercurius-js/mercurius/issues/406
=> Add subscription hooks to Mercurius

docs/integrations/README.md, docs/integrations/type-graphql.md
I've added integration docs for TypeGraphQL, similar to the nexus one 😉
=> Add TypeGraphQL integration docs

docs/hooks.md, examples/hooks-gateway.js, index.d.ts, lib/gateway.js, lib/gateway/make-resolver.js, lib/handlers.js, lib/hooks.js, test/gateway/hooks.js, test/gateway/subscription-hooks.js, test/types/index.ts
Closes: https://github.com/mercurius-js/mercurius/issues/415
=> Add service metadata parameter to gateway hooks

docs/api/options.md, docs/federation.md, docs/hooks.md, docs/integrations/README.md, docs/typescript.md, docsify/sidebar.md, static/graphiql.html
- fixed a few links
- fastify-gql to Mercurius in graphiql.html
=> docs: Fix some links

lib/gateway.js, test/aliases.js, test/gateway/aliases.js
Fixes: https://github.com/mercurius-js/mercurius/issues/428
I have added tests for both gateway and non-gateway modes of operation. Next, I'll run the benchmarks and update here to make sure that this is the right approach.
=> Fix for gateway alias resolution errors

lib/gateway/make-resolver.js, test/directives.js, test/gateway/include-directive.js, test/gateway/skip-directive.js
Fixes: https://github.com/mercurius-js/mercurius/issues/432
Note, I've also included tests for non-gateway mode
=> Add fix for input variable handling by query directives in the gateway

docs/integrations/README.md, docs/integrations/prisma.md, docsify/sidebar.md
Added Prisma integration to docs to help with #352 🙂
=> feat(docs) :added prisma integration with mercurius

docs/subscriptions.md, index.d.ts, test/gateway/pollingInterval.js
- Fix typescript types for unions are not following the real names in the code: https://github.com/mercurius-js/mercurius/blob/master/index.js#L294 https://github.com/mercurius-js/mercurius/blob/master/index.js#L319
- The TypeScript section is not in the main README TOC
- Subscriptions docs have a mistake in the TOC
=> fix test race condition, union types, & toc name

index.d.ts
=> fix mergeInfo type conflict

docs/api/options.md, index.d.ts, lib/gateway/make-resolver.js, lib/subscription-client.js, test/gateway/subscription.js, test/subscription-client.js, test/types/index.ts
=> feat(gateway): add rewriteConnectionInitPayload option

lib/gateway.js, lib/gateway/find-value-types.js, test/gateway/value-types.js
Implements value type handling as discussed in #499
Leaves an open todo as described in find-value-types.js:
```
/**
* TODO: it should be checked whether all types with the same name have the exact same fields,
* incl. types, subtypes and nullability
* If that is not the case, I would argue that throwing would be the best approach
*/
```
=> feat(gateway): handle value types

lib/gateway.js, test/gateway/value-types.js
adds support for nested value types
#499
=> feat(gateway): add support for nested value types

lib/subscription-connection.js
=> Fixed compatibility with ws@8.0.0

lib/subscription-connection.js, test/subscription-client.js
> this merges into the dependabot PR which bumps package ws to semver major 8: https://github.com/mercurius-js/mercurius/pull/566
Addresses the breaking changes in ws@8
=> fix: ws@8 fixes

lib/federation.js, test/federation.js
Fixes https://github.com/mercurius-js/mercurius/issues/580
=> Do not crash with federationMetadata with a schema definition

docs/plugins.md
=> docs: add mercurius-apollo-tracing

examples/gateway-subscription.js, lib/subscription-client.js, lib/subscription-connection.js, lib/subscription-protocol.js, lib/subscription.js, static/main.js, test/subscription-client.js, test/subscription-connection.js, test/subscription-protocol.js
Added the support to graqphql_transport_ws.
closes #574
=> feat: add support to graqphql_transport_ws

docs/api/options.md, index.d.ts, lib/errors.js, test/errors.js, test/types/index.ts
=> feat: add status code support to ErrorWithProps

README.md
Add faq page to readme docs links
=> Update readme.md for faq page

README.md
=> chore: add logo

lib/gateway/request.js, test/gateway/request.js
fix the CI fails here https://github.com/mercurius-js/auth/pull/46
=> fix wrapping FederatedError

docs/plugins.md
=> docs: Add mercurius-postgraphile to plugin docs

docs/loaders.md, index.js, test/loaders.js
=> Include the info object in loaders when the loader cache is off

docs/api/options.md, index.js, package.json, test/cache.js, test/options.js
This PR adds new options in mercurius which can be passed to the graphql-jit compiler.
Closes #390
=> Added graphql-jit compiler options

docs/integrations/type-graphql.md
Added a section in the `type-graphql` integration docs about solving problems with validation error details that came out from #458 ticket.
Closes #458
=> docs: update type-graphql integration doc

index.d.ts, test/types/index.ts
Fix for https://github.com/mercurius-js/mercurius/issues/698
=> fix: add service.keepAlive prop to types

docsify/sidebar.md
=> Fix sidebar link

lib/gateway.js, lib/gateway/make-resolver.js, test/gateway/fix-726.js, test/gateway/retry-failed-services.js, test/gateway/schema.js
=> [Gateway] Correctly resolve references returned from top-level resolvers

docs/integrations/README.md, docs/integrations/nestjs.md, docsify/sidebar.md
Hi,
I hope this is ok. I thought it would be good to add NestJS in the integrations. 
Scott
=> feat(docs): add nestjs integration docs

index.d.ts, lib/errors.js, lib/routes.js, lib/subscription.js, package.json, test/subscription.js
`fastify-static & fastify-error & fastify-websocket -> @fastify/static & @fastify/error & @fastify/websocket`
=> Use new fastify plugin names for `@fastify/static` & `@fastify/error` & `@fastify/websocket` (#791)

docs/integrations/open-telemetry.md
fixes #634 
I tested it in StackBlitz.
https://stackblitz.com/edit/node-vxhsuc?file=provider.js
=> docs: update open telemetry example

index.js, test/cache.js
=> Fix for cached jit query is not a function

index.js, test/gateway/remote-services.js
=> better CI stability

docs/api/options.md, docs/federation.md, examples/gateway.js, index.d.ts, lib/gateway/make-resolver.js, lib/gateway/request.js, lib/gateway/service-map.js, test/gateway/set-response-headers.js, test/types/index.ts
Addresses https://github.com/mercurius-js/mercurius/issues/777
Letting subgraphs/downstream services set headers in federation mode
=> Set Headers from subgraphs

lib/subscriber.js, lib/subscription.js, package.json
=> Update to readable-stream v4

docs/plugins.md
relates to #694 and https://github.com/mercurius-js/mercurius/issues/732
=> docs: list mercurius-logging plugin

index.d.ts
Like https://github.com/fastify/fastify/issues/4222
=> fix: add constraints for TypeScript 4.8 compatibility

docs/api/options.md, docs/http.md, lib/errors.js, tap-snapshots/test/routes.js.test.cjs, test/errors.js, test/routes.js
=> Breaking Change: statusCode 200 for all responses

docs/plugins.md
this PR is for add new plugin into documentation 
https://www.npmjs.com/package/mercurius-fetch
=> Update Plugins documentation

index.d.ts, test/types/index.ts
This PR updates types related to various hooks
Closes #877 
cc @simoneb
=> Fix hooks types

index.js, lib/persistedQueryDefaults.js, package.json
=> Bumped tiny-lru to v10.x

index.js, test/app-decorator.js
This PR fixes is required to support properly the gateway.
=> fix: add __resolveReference support

docs/lifecycle.md
Fix code block by removing redundant backticks.
=> docs: fix code block

index.js, test/app-decorator.js
=> schema option: Better error handling when providing arrays with non-string schemas

package.json
Ref https://github.com/zalando-incubator/graphql-jit/issues/241
=> Lock graphql-jit to v0.8.4

docs/plugins.md
Just updating the altair graphql website in plugins.md. Feel free to make the change yourself and close this PR if this isn't the kind of PR you like to receive 🙂 I won't take it personally 😄
=> Update altair graphql website in plugins.md

test/subscription-connection.test.js
Proposals:
- migrated `subscription-connetions.test.js` from `tap` to `node:test` 🔥
=> test: migrated subscription-connetions.test.js from tap to node:test
